### ISSUE TITLE
Data hosting for APE task is unstable

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#463]
Currently our integration test for the ArgumentPairExtraction task is failing, probably because the server hosting the data is unstable. @pfliu-nlp would you be able to take a look at this and maybe move the data to a more stable hosting location?

```
======================================================================
ERROR: test_datalab_loader (integration_tests.argument_pair_extraction_test.ArgumentPairExtractionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/ExplainaBoard/ExplainaBoard/integration_tests/argument_pair_extraction_test.py", line 24, in test_datalab_loader
    data = loader.load()
  File "/home/runner/work/ExplainaBoard/ExplainaBoard/explainaboard/loaders/loader.py", line 154, in load
    dataset_loaded_data = self._dataset_file_loader.load(
  File "/home/runner/work/ExplainaBoard/ExplainaBoard/explainaboard/loaders/file_loader.py", line 335, in load
    raw_data = self.load_raw(data, source)
  File "/home/runner/work/ExplainaBoard/ExplainaBoard/explainaboard/loaders/file_loader.py", line 567, in load_raw
    dataset = load_dataset(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/datalabs/load.py", line 2144, in load_dataset
    builder_instance.download_and_prepare(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/datalabs/builder.py", line 741, in download_and_prepare
    self._download_and_prepare(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/datalabs/builder.py", line 838, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "/home/runner/.cache/expressai/modules/datasets_modules/datalab/ape/6a47b551465788cfbfe4158930982d8dc72e77f95d45301a122e560683f1a9b9/ape.py", line 75, in _split_generators
    train_path = dl_manager.download_and_extract(_TRAIN_DOWNLOAD_URL)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/datalabs/utils/download_manager.py", line 322, in download_and_extract
    return self.extract(self.download(url_or_urls))
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/datalabs/utils/download_manager.py", line 221, in download
    downloaded_path_or_paths = map_nested(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/datalabs/utils/py_utils.py", line 297, in map_nested
    return function(data_struct)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/datalabs/utils/download_manager.py", line 248, in _download
    return cached_path(url_or_filename, download_config=download_config)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/datalabs/utils/file_utils.py", line 344, in cached_path
    output_path = get_from_cache(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/datalabs/utils/file_utils.py", line 720, in get_from_cache
    raise ConnectionError(f"Couldn't reach {url} ({repr(head_error)})")
ConnectionError: Couldn't reach https://cdatalab1.oss-cn-beijing.aliyuncs.com/argument_pair_extraction/ape/train.txt (ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='cdatalab1.oss-cn-beijing.aliyuncs.com', port=443): Read timed out. (read timeout=10)")))

----------------------------------------------------------------------
```

**Comment by odashi** [comment]
This seems to happen by the same cause with #412 that should be fixed similarly.

**Comment by pfliu-nlp** [comment]
This should be fixed by this PR: https://github.com/ExpressAI/DataLab/pull/344

**Comment by neubig** [comment]
Thank you!
